# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hello_world_block_design/hello_world_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hello_world_block_design || ORIG_REF_NAME==hello_world_block_design} -quiet] -quiet

# IP: bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hello_world_block_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==hello_world_block_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.gen/sources_1/bd/hello_world_block_design/hello_world_block_design_ooc.xdc
