# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.srcs/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'hello_world_block_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.gen/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_world_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.gen/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_world_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.srcs/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'hello_world_block_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.gen/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_world_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/HDL/Hello_World/Hello_World.gen/sources_1/bd/hello_world_block_design/ip/hello_world_block_design_zynq_ultra_ps_e_0_0/hello_world_block_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_world_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
