# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_blink_constrains.xdc

# Block Designs: bd/led_blink_block_design/led_blink_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blink_block_design || ORIG_REF_NAME==led_blink_block_design} -quiet] -quiet

# IP: bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blink_block_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==led_blink_block_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/led_blink_block_design/ip/led_blink_block_design_led_blink_0_0/led_blink_block_design_led_blink_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blink_block_design_led_blink_0_0 || ORIG_REF_NAME==led_blink_block_design_led_blink_0_0} -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.gen/sources_1/bd/led_blink_block_design/led_blink_block_design_ooc.xdc
