#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 16 20:54:19 CEST 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim and2_behav -key {Behavioral:sim_1:Functional:and2} -tclbatch and2.tcl -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/inverter_behav.wcfg -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/nand2_behav.wcfg -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/and2_behav.wcfg -log simulate.log"
xsim and2_behav -key {Behavioral:sim_1:Functional:and2} -tclbatch and2.tcl -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/inverter_behav.wcfg -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/nand2_behav.wcfg -view /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/Gate Level Playground/Gate Level Playground/and2_behav.wcfg -log simulate.log

