# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.srcs/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'led_blink_block_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.gen/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_blink_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.gen/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_blink_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.srcs/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'led_blink_block_design_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.gen/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_blink_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/LED_Blink/LED_Blink.gen/sources_1/bd/led_blink_block_design/ip/led_blink_block_design_zynq_ultra_ps_e_0_0/led_blink_block_design_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_blink_block_design_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
