# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/nbody_simulation/nbody/nbodyproj.srcs/sources_1/bd/design_fp_add/ip/design_fp_add_floating_point_0_0/design_fp_add_floating_point_0_0.xci
# IP: The module: 'design_fp_add_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/nbody_simulation/nbody/nbodyproj.srcs/sources_1/bd/design_fp_add/ip/design_fp_add_floating_point_0_0/design_fp_add_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fp_add_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/nbody_simulation/nbody/nbodyproj.srcs/sources_1/bd/design_fp_add/ip/design_fp_add_floating_point_0_0/design_fp_add_floating_point_0_0.xci
# IP: The module: 'design_fp_add_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/nbody_simulation/nbody/nbodyproj.srcs/sources_1/bd/design_fp_add/ip/design_fp_add_floating_point_0_0/design_fp_add_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fp_add_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
