# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/call_me_utka/Documents/Projects/aes-ultra96-v2-playground/nbody_simulation/src/nbody.xdc

# Block Designs: bd/design_fp_mult/design_fp_mult.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_mult || ORIG_REF_NAME==design_fp_mult} -quiet] -quiet

# IP: bd/design_fp_mult/ip/design_fp_mult_floating_point_0_0/design_fp_mult_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_mult_floating_point_0_0 || ORIG_REF_NAME==design_fp_mult_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_fp_invsqrt/design_fp_invsqrt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_invsqrt || ORIG_REF_NAME==design_fp_invsqrt} -quiet] -quiet

# IP: bd/design_fp_invsqrt/ip/design_fp_invsqrt_floating_point_0_0/design_fp_invsqrt_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_invsqrt_floating_point_0_0 || ORIG_REF_NAME==design_fp_invsqrt_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_fp_add/design_fp_add.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_add || ORIG_REF_NAME==design_fp_add} -quiet] -quiet

# IP: bd/design_fp_add/ip/design_fp_add_floating_point_0_0/design_fp_add_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fp_add_floating_point_0_0 || ORIG_REF_NAME==design_fp_add_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_float_to_fixed/design_float_to_fixed.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_float_to_fixed || ORIG_REF_NAME==design_float_to_fixed} -quiet] -quiet

# IP: bd/design_float_to_fixed/ip/design_float_to_fixed_floating_point_0_0/design_float_to_fixed_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_float_to_fixed_floating_point_0_0 || ORIG_REF_NAME==design_float_to_fixed_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_fixed_to_float/design_fixed_to_float.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fixed_to_float || ORIG_REF_NAME==design_fixed_to_float} -quiet] -quiet

# IP: bd/design_fixed_to_float/ip/design_fixed_to_float_floating_point_0_0/design_fixed_to_float_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_fixed_to_float_floating_point_0_0 || ORIG_REF_NAME==design_fixed_to_float_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_apb_bridge_0_0/design_1_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_apb_bridge_0_0 || ORIG_REF_NAME==design_1_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uart16550_0_0/design_1_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uart16550_0_0 || ORIG_REF_NAME==design_1_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/design_fp_mult/design_fp_mult_ooc.xdc

# XDC: bd/design_fp_invsqrt/design_fp_invsqrt_ooc.xdc

# XDC: bd/design_fp_add/design_fp_add_ooc.xdc

# XDC: bd/design_float_to_fixed/design_float_to_fixed_ooc.xdc

# XDC: bd/design_fixed_to_float/design_fixed_to_float_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
